import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getPacket, getPackets } from '@/lib/journal';

interface Params {
  jurisdiction: string;
  workstream: string;
  journalId: string;
}

export async function generateStaticParams(): Promise<Params[]> {
  const packets = getPackets();
  return packets.map((p) => ({
    jurisdiction: p.jurisdiction.toLowerCase(),
    workstream: p.workstream,
    journalId: p.journal_id,
  }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<Params>;
}): Promise<Metadata> {
  const { journalId, jurisdiction, workstream } = await params;
  const packet = getPacket(journalId);
  if (!packet) return { title: 'Article not found' };

  return {
    title: packet.title,
    description: packet.summary.slice(0, 160),
    alternates: {
      canonical: `https://peerpulse.app/journal/${jurisdiction}/${workstream}/${journalId}`,
    },
    openGraph: {
      title: packet.title,
      description: packet.summary.slice(0, 160),
    },
  };
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

export default async function JournalArticlePage({
  params,
}: {
  params: Promise<Params>;
}) {
  const { journalId, jurisdiction, workstream } = await params;
  const packet = getPacket(journalId);

  if (!packet) notFound();

  const wsLabel =
    packet.workstream.charAt(0).toUpperCase() + packet.workstream.slice(1);
  const jurLabel = jurisdiction.toUpperCase();

  return (
    <div className="pw-article-wrap">
      {/* JSON-LD */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Article',
            headline: packet.title,
            description: packet.summary.slice(0, 160),
            datePublished: packet.source_date,
            author: {
              '@type': 'Organization',
              name: packet.node_label ?? packet.node_id,
            },
            publisher: {
              '@type': 'Organization',
              name: 'PeerPulse',
              url: 'https://peerpulse.app',
            },
          }),
        }}
      />

      {/* Breadcrumb */}
      <div className="pw-breadcrumb">
        <Link href="/">Home</Link> ›{' '}
        <Link href="/journal">Journal</Link> ›{' '}
        {jurLabel} ›{' '}
        {wsLabel}
      </div>

      {/* Canonical route display */}
      <div className="pw-article-route">
        peerpulse.app/journal/{jurisdiction}/{workstream}/{journalId}
      </div>

      {/* Meta */}
      <div className="pw-article-meta">
        <span className={`pw-ws-badge ${packet.workstream}`}>{wsLabel}</span>
        <span className="pw-article-date">{fmtDate(packet.source_date)}</span>
        <span
          style={{
            marginLeft: 'auto',
            fontSize: '11px',
            color: 'var(--text-3)',
            display: 'flex',
            alignItems: 'center',
            gap: '5px',
          }}
        >
          <span
            style={{
              width: '5px',
              height: '5px',
              borderRadius: '50%',
              background: '#4ade80',
              display: 'inline-block',
            }}
          />
          {packet.node_label ?? packet.node_id}
        </span>
      </div>

      {/* Title */}
      <h1 className="pw-article-h1">{packet.title}</h1>

      {/* AI extraction warning */}
      {!packet.human_reviewed && (
        <div className="pw-ai-warn">
          <span style={{ fontSize: '16px' }}>⚠️</span>
          <div className="pw-ai-warn-text">
            <strong style={{ color: 'var(--tab)' }}>AI-extracted · Not human-reviewed.</strong>{' '}
            This summary was generated by an AI pipeline from primary source documents. Verify claims
            against the cited sources before relying on specific figures or legal provisions.
          </div>
        </div>
      )}

      {/* Extraction notes banner */}
      {packet.extraction_notes && (
        <div className="pw-extract-warn">
          <span style={{ fontSize: '16px' }}>🚩</span>
          <div className="pw-extract-warn-text">{packet.extraction_notes}</div>
        </div>
      )}

      {/* Summary */}
      <div className="pw-a-section">
        <div className="pw-a-label">Summary</div>
        <p className="pw-summary-text">{packet.summary}</p>
      </div>

      {/* Key points */}
      <div className="pw-a-section">
        <div className="pw-a-label">Key points</div>
        <div className="pw-kp-list">
          {packet.key_points.map((kp, i) => (
            <div className="pw-kp" key={i}>
              <div className="pw-kp-dot" />
              <div className="pw-kp-body">
                <div className="pw-kp-text">{kp.text}</div>
                <div className="pw-kp-ref">{kp.source_ref}</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Citations */}
      <div className="pw-a-section">
        <div className="pw-a-label">Primary sources</div>
        {packet.citations.map((cite, i) => {
          const isUnverified = cite.excerpt.toLowerCase().startsWith('unverified');
          return (
            <div className="pw-citation" key={i}>
              <a
                href={cite.url}
                target="_blank"
                rel="noopener noreferrer"
                className="pw-cite-source"
              >
                {cite.source_ref} ↗
              </a>
              <div
                className={`pw-cite-excerpt${isUnverified ? ' pw-cite-unverified' : ''}`}
              >
                {cite.excerpt}
              </div>
            </div>
          );
        })}
      </div>

      {/* Journal node */}
      <div className="pw-a-section">
        <div className="pw-a-label">Journal node</div>
        <div className="pw-node-card">
          <div className="pw-node-icon">⚡</div>
          <div>
            <div className="pw-node-name">{packet.node_label ?? 'Journal Node'}</div>
            <div className="pw-node-id">{packet.node_id}</div>
          </div>
          <div className="pw-node-active">Active</div>
        </div>
      </div>

      {/* Poll card */}
      {packet.has_poll && packet.poll_question && (
        <div className="pw-a-section">
          <div className="pw-a-label">Related survey</div>
          <div className="pw-survey-card">
            <div className="pw-survey-label">📊 Open Poll</div>
            <div className="pw-survey-q">{packet.poll_question}</div>
            {packet.poll_publisher && (
              <div className="pw-survey-pub">{packet.poll_publisher}</div>
            )}
            <Link href="/download" className="pw-survey-btn">
              Vote in app →
            </Link>
          </div>
        </div>
      )}

      {/* Subscribe CTA */}
      <Link href="/download" className="pw-open-app">
        📲 Subscribe in app — get jurisdiction notifications
      </Link>
    </div>
  );
}
